[custom]
;不要随意改变关键字，否则会导致出错
;由acl4SSR规则修改~


;设置规则标志位
;ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
;ruleset=😒 审计规则,https://raw.githubusercontent.com/LITTLESITE/clash-/main/shenji.list
;ruleset=⏬ 下载服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🚀 规则选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CN.list
;ruleset=🔀 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
;ruleset=🔀 直连,[]GEOIP,LAN
;ruleset=🔀 直连,FINAL
ruleset=手动切换,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=手动切换`select`.*
custom_proxy_group=CN`select`(CN|HK|TW|cn|hk|tw|中国|香港|台湾).*
custom_proxy_group=KR`select`(KR|kr|韩国).*
custom_proxy_group=JP`select`(JP|jp|日本).*
custom_proxy_group=SG`select`(SG|sg|新加坡|狮城).*
custom_proxy_group=US`select`(US|us|美国).*
;custom_proxy_group=CA`select`(CA|ca).*
;custom_proxy_group=RU`select`(RU|ru).*
;custom_proxy_group=GB`select`(GB|gb).*
;custom_proxy_group=DE`select`(DE|de).*
;custom_proxy_group=FR`select`(FR|fr).*
custom_proxy_group=other`select`(other).*
custom_proxy_group=自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=负载均衡`load-balance`.*`https://www.google.com/favicon.ico`300,,50
;custom_proxy_group=规则选择`select`[]负载均衡`[]自动选择

enable_rule_generator=true
overwrite_original_rules=true

;e.g.
;custom_proxy_group=美国节点`url-test`(美国|US)`http://www.gstatic.com/generate_204`300,,150
;  - name: 自动选择
;    type: url-test
;    url: 'http://www.gstatic.com/generate_204'
;    interval: 300
;    tolerance: 50
;    proxies:
;  - name: 负载均衡
;    type: load-balance
;    strategy: consistent-hashing
;    url: http://www.gstatic.com/generate_204
;    interval: 300
;    tolerance: 50
;    proxies:


