name: down file
# 触发条件
on:
  workflow_dispatch:
  #schedule:
   #- cron: '0 21 * * *'
  #实际时间：+ 8小时  = 5:00
  #这个实际每天5:00执行
  #表达式生成  https://crontab.guru/
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #DDAL_EMAIL: ${{ secrets.DDAL_EMAIL }}
      #DDAL_PASSWORD: ${{ secrets.DDAL_PASSWORD }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 执行任务 - down
        run: |
          cd ./tools
          curl -o CF_proxy_IP.zip https://d.kstore.dev/download/4901/tools/CF_proxy_IP.zip
          curl -o nodesCatch.7z https://d.kstore.dev/download/4901/tools/nodesCatch.7z
          curl -o WinXray.7z https://d.kstore.dev/download/4901/tools/WinXray.7z
          curl -o TVBox_q215613905_20230302-0924.apk https://rxsub.vercel.app/tvbox/apk/TVBox_q215613905_20230302-0924.apk
          
          #wget -q -O cf.yaml https://tt.vg/rx

      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') down done"
          git pull --rebase
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          branch: main
